import type { Metadata } from 'next'
import './globals.css'
import { robotoFont } from '@/lib'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${robotoFont.variable} font-roboto antialiased`}>
                {children}
            </body>
        </html>
    )
}
